"""init schema

Revision ID: 6031768b8c60
Revises: 
Create Date: 2026-07-02 04:58:10.894799

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6031768b8c60'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('class_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('class_number', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('social_provider', sa.String(length=50), nullable=True),
    sa.Column('social_id', sa.String(length=255), nullable=True),
    sa.Column('class_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], name='fk_users_class'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('assignments',
    sa.Column('assignment_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.BigInteger(), nullable=False),
    sa.Column('class_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], name='fk_assignments_class'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.user_id'], name='fk_assignments_teacher'),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('attendance_records',
    sa.Column('attendance_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('attendance_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='fk_attendance_user'),
    sa.PrimaryKeyConstraint('attendance_id')
    )
    op.create_table('notices',
    sa.Column('notice_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('class_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], name='fk_notices_author'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], name='fk_notices_class'),
    sa.PrimaryKeyConstraint('notice_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('token_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='fk_refresh_tokens_user'),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_table('documents',
    sa.Column('document_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.BigInteger(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_id'], name='fk_documents_assignment'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('stage1_assignment_details',
    sa.Column('detail_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.BigInteger(), nullable=False),
    sa.Column('parameter_guide', sa.JSON(), nullable=True),
    sa.Column('default_parameters', sa.JSON(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('guideline', sa.Text(), nullable=True),
    sa.Column('persona', sa.String(length=100), nullable=True),
    sa.Column('hallucination_types', sa.JSON(), nullable=True),
    sa.Column('hallucination_hint', sa.Text(), nullable=True),
    sa.Column('expected_hallucination_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_id'], name='fk_stage1_details_assignment'),
    sa.PrimaryKeyConstraint('detail_id')
    )
    op.create_table('student_assignment_status',
    sa.Column('status_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('assignment_id', sa.BigInteger(), nullable=False),
    sa.Column('progress_status', sa.String(length=30), nullable=True),
    sa.Column('best_score', sa.Integer(), nullable=True),
    sa.Column('remaining_attempts', sa.Integer(), nullable=True),
    sa.Column('total_literacy_score', sa.Integer(), nullable=True),
    sa.Column('bias_found_count', sa.Integer(), nullable=True),
    sa.Column('learning_duration_sec', sa.Integer(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_id'], name='fk_status_assignment'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='fk_status_user'),
    sa.PrimaryKeyConstraint('status_id'),
    sa.UniqueConstraint('user_id', 'assignment_id', name='uq_student_assignment')
    )
    op.create_table('submissions',
    sa.Column('submission_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('assignment_id', sa.BigInteger(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.Column('submitted_answer', sa.Text(), nullable=True),
    sa.Column('final_parameters', sa.JSON(), nullable=True),
    sa.Column('current_score', sa.Integer(), nullable=True),
    sa.Column('is_final', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_id'], name='fk_submissions_assignment'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='fk_submissions_user'),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_table('document_chunks',
    sa.Column('chunk_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], name='fk_document_chunks_document'),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_table('evaluations',
    sa.Column('evaluation_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.BigInteger(), nullable=False),
    sa.Column('factuality_score', sa.Integer(), nullable=True),
    sa.Column('relevance_score', sa.Integer(), nullable=True),
    sa.Column('social_impact_score', sa.Integer(), nullable=True),
    sa.Column('ai_understanding_score', sa.Integer(), nullable=True),
    sa.Column('data_literacy_score', sa.Integer(), nullable=True),
    sa.Column('problem_solving_score', sa.Integer(), nullable=True),
    sa.Column('ai_ethics_score', sa.Integer(), nullable=True),
    sa.Column('action_plan_score', sa.Integer(), nullable=True),
    sa.Column('total_literacy_score', sa.Integer(), nullable=True),
    sa.Column('misconception_tags', sa.JSON(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('evaluation_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], name='fk_evaluations_submission'),
    sa.PrimaryKeyConstraint('evaluation_id')
    )
    op.create_table('stage1_attempts',
    sa.Column('attempt_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('assignment_id', sa.BigInteger(), nullable=False),
    sa.Column('submission_id', sa.BigInteger(), nullable=True),
    sa.Column('student_prompt', sa.Text(), nullable=True),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_id'], name='fk_stage1_attempts_assignment'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], name='fk_stage1_attempts_submission'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='fk_stage1_attempts_user'),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_table('stage2_assignment_details',
    sa.Column('detail_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('persona', sa.String(length=100), nullable=True),
    sa.Column('hallucinated_ai_answer', sa.Text(), nullable=True),
    sa.Column('hallucination_types', sa.JSON(), nullable=True),
    sa.Column('expected_error_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_id'], name='fk_stage2_details_assignment'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], name='fk_stage2_details_document'),
    sa.PrimaryKeyConstraint('detail_id')
    )
    op.create_table('stage2_correction_submissions',
    sa.Column('correction_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('assignment_id', sa.BigInteger(), nullable=False),
    sa.Column('submission_id', sa.BigInteger(), nullable=True),
    sa.Column('selected_error', sa.Text(), nullable=True),
    sa.Column('student_correction', sa.Text(), nullable=True),
    sa.Column('is_passed', sa.Boolean(), nullable=True),
    sa.Column('final_answer', sa.Text(), nullable=True),
    sa.Column('feedback_detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_id'], name='fk_stage2_correction_assignment'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], name='fk_stage2_correction_submission'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='fk_stage2_correction_user'),
    sa.PrimaryKeyConstraint('correction_id')
    )
    op.create_table('stage2_highlight_submissions',
    sa.Column('highlight_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('assignment_id', sa.BigInteger(), nullable=False),
    sa.Column('submission_id', sa.BigInteger(), nullable=True),
    sa.Column('highlighted_text', sa.Text(), nullable=True),
    sa.Column('start_index', sa.Integer(), nullable=True),
    sa.Column('end_index', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=50), nullable=True),
    sa.Column('highlight_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('correction_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_id'], name='fk_stage2_highlight_assignment'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], name='fk_stage2_highlight_submission'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='fk_stage2_highlight_user'),
    sa.PrimaryKeyConstraint('highlight_id')
    )
    op.create_table('stage2_error_answers',
    sa.Column('answer_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.BigInteger(), nullable=False),
    sa.Column('detail_id', sa.BigInteger(), nullable=True),
    sa.Column('error_sentence', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=50), nullable=True),
    sa.Column('start_index', sa.Integer(), nullable=True),
    sa.Column('end_index', sa.Integer(), nullable=True),
    sa.Column('correct_sentence', sa.Text(), nullable=True),
    sa.Column('hallucination_reason', sa.Text(), nullable=True),
    sa.Column('evidence_sentence', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_id'], name='fk_stage2_answers_assignment'),
    sa.ForeignKeyConstraint(['detail_id'], ['stage2_assignment_details.detail_id'], name='fk_stage2_answers_detail'),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_foreign_key(
        "fk_classes_teacher",
        "classes",
        "users",
        ["teacher_id"],
        ["user_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_classes_teacher", "classes", type_="foreignkey")
    op.drop_table('stage2_error_answers')
    op.drop_table('stage2_highlight_submissions')
    op.drop_table('stage2_correction_submissions')
    op.drop_table('stage2_assignment_details')
    op.drop_table('stage1_attempts')
    op.drop_table('evaluations')
    op.drop_table('document_chunks')
    op.drop_table('submissions')
    op.drop_table('student_assignment_status')
    op.drop_table('stage1_assignment_details')
    op.drop_table('documents')
    op.drop_table('refresh_tokens')
    op.drop_table('notices')
    op.drop_table('attendance_records')
    op.drop_table('assignments')
    op.drop_table('users')
    op.drop_table('classes')
    # ### end Alembic commands ###
